### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by BUGBEAR7** [kodi-connect/kodi-connect-addon#35]
Hello 
I have been using this addon for last 1 year in my Kodi Krypton , but recently have to update the Kodi because few addon now does not support in old Kodi build.
Recently updated to Kodi Matrix as we all it does not support old python so I was wondering will there be any update for this addon

Thanks

**Comment by tkislan** [comment]
Hello,
yes, I've done the compatibility update here: https://github.com/kodi-connect/kodi-connect-addon/pull/34
But it didn't help the person who was asking for it
And my device doesn't yet have the update to new Kodi

Can you try the following version?
[plugin.video.kodiconnect-0.3.0.zip](https://github.com/kodi-connect/kodi-connect-addon/files/6539027/plugin.video.kodiconnect-0.3.0.zip)

**Comment by BUGBEAR7** [comment]
Hello
I just tried to install it , it gave me same error for missing python 2.14.0
I edited the addon.xml
<import addon="xbmc.python" version="3.0.0"/>

got the error
2021-05-25 17:41:02.242 T:11364    INFO <general>: initializing python engine.
2021-05-25 17:41:02.266 T:11364 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-05-25 17:41:02.273 T:11364   ERROR <general>: Skipped 1 duplicate messages..
2021-05-25 17:41:02.273 T:11364   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: argument 1 must be str, not bytes
                                                   Traceback (most recent call last):
                                                     File "C:\Users\M-C\AppData\Roaming\Kodi\addons\plugin.video.kodiconnect\plugin.py", line 29, in <module>
                                                       logger.debug(u'RESOURCES_PATHs: {}, {}'.format(RESOURCES_PATH, LIB_RESOURCES_PATH))
                                                     File "C:\Users\M-C\AppData\Roaming\Kodi\addons\plugin.video.kodiconnect\resources\connect\logger.py", line 7, in debug
                                                       _log(message)
                                                     File "C:\Users\M-C\AppData\Roaming\Kodi\addons\plugin.video.kodiconnect\resources\connect\logger.py", line 4, in _log
                                                       xbmc.log(u'[KodiConnect] {}'.format(message).encode('utf-8'), level=xbmc.LOGDEBUG)
                                                   TypeError: argument 1 must be str, not bytes
                                                   -->End of Python script error report<--
                                                   
2021-05-25 17:41:02.387 T:11364    INFO <general>: Python interpreter stopped
2021-05-25 17:41:02.407 T:10460   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.kodiconnect/
2021-05-25 17:41:02.428 T:8400    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kodiconnect/) failed

**Comment by tkislan** [comment]
Ah thank you .. this should be easy to fix .. will let you know when the new version is available

**Comment by BUGBEAR7** [comment]
Thanks 
Will be waiting of that :)

**Comment by BUGBEAR7** [comment]
Hi mate 
Any update on this ?

**Comment by tkislan** [comment]
[plugin.video.kodiconnect-0.3.1.zip](https://github.com/kodi-connect/kodi-connect-addon/files/6564155/plugin.video.kodiconnect-0.3.1.zip)

It should fix the above problem .. but there still might be other issues .. please let me know if you have some other error thrown

**Comment by BUGBEAR7** [comment]
Thanks for the response

I installed it on a fresh new Kodi installation.
It installed correctly , after that I putted my login details . A pop up appeared that it is connected 
I checked it at https://kodiconnect.kislan.sk/devices . It showed that device is connected but command of playing anything is not working though Alexa did said "Playing xxxxx in Kodi" but playback did not start . After a minute a two I got another pop up saying "Kodi Connect Disconnected" . I confirm this on webpage the previously connected device was not disconnected anymore.

I have only one error now in the log related to this plugin.video.kodiconnect

2021-05-29 13:09:36.930 T:2568     INFO <general>: CPythonInvoker(6, C:\Users\M-C\AppData\Roaming\Kodi\addons\plugin.video.kodiconnect\service.py): script successfully run
2021-05-29 13:09:37.051 T:2568     INFO <general>: Python interpreter interrupted by user
2021-05-29 13:09:39.520 T:6608     INFO <general>: initializing python engine.
2021-05-29 13:09:39.597 T:6608     INFO <general>: CPythonInvoker(37, C:\Users\M-C\AppData\Roaming\Kodi\addons\script.embuary.helper\default.py): script successfully run
2021-05-29 13:09:39.691 T:6608     INFO <general>: Python interpreter stopped
2021-05-29 13:09:43.774 T:4840     INFO <general>: initializing python engine.
2021-05-29 13:09:43.886 T:4840  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-05-29 13:09:44.043 T:4840    ERROR <general>: Skipped 1 duplicate messages..
2021-05-29 13:09:44.043 T:4840    ERROR <general>: C:\Users\M-C\AppData\Roaming\Kodi\addons\plugin.video.kodiconnect\resources\lib\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
                                                     warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
                        
I restarted the Kodi at start pop up appears as usual "Kodi Connect Connected" but after few minute another pop up comes saying it is disconnected . Same goes on webpage at Kodi startup the Connected is "Yes" but as the pop up appears in Kodi it goes to "No"

**Comment by BUGBEAR7** [comment]
I also tested the older version on my Kodi Leia which is installed on a Mac, it is working fine as expected so setup to the Skill is correct. I guess there is something to be done in addon

**Comment by BUGBEAR7** [comment]
Hello
Have you checked it ?

**Comment by tkislan** [comment]
@BUGBEAR7 
Yes, sorry for the late reply
I actually can't figure out what might be wrong only from the portion you provided
Would it be possible to try the same thing, and send the full kodi.log file?

**Comment by BUGBEAR7** [comment]
Sure , I will send it today

**Comment by flos06** [comment]
Any  progress on this? Or do you still need a full log file tkislan? In which case I can try to provide one.

**Comment by flos06** [comment]
So I've attached a logfile.

At first it says connected and then I try to give a command to watch a movie. In this case the father. Alexa replies with getting the father from kodi. Nothing happens however. At this point it states that kodi connect is still connected.

A few minutes later however kodi connect is no longer connected and in the log file it says connection closed as seen here:

Log:
https://paste.ee/p/cH0g8

**Comment by flos06** [comment]
Not to rush you but have you found  the time to take a look? I would really love to get this working as it seems great :)

**Comment by tkislan** [comment]
Yes, thank you ... I did take a look at the logs, but nothing irregular there .. no error at all .. so that's why it's taking longer
I will probably need to install it locally, and try what might be the problem

**Comment by flos06** [comment]
Alright thanks for trying to figure it out

**Comment by Motisu** [comment]
Also waiting for a fix. This addon is the only reason that I an not upgrading to matrix.
Good luck!

**Comment by Marcagodbout** [comment]
Hello tkislan,

Any update on the status of the addon?

First off thank you for this addon I have been using it for a long time now and love it, unfortunately I needed to upgrade all my kodi instances to 19 as well and was extremely sad when I found out they changed the python and kodi-connect stopped working, so THANK YOU for this add-on and taking the time to create and update it. I am very pleased to see you are getting it ready for 19.

I tried the install the zip you linked early in this post. As the others stated it connects initially but after a minute it just disconnects with no error. I ran it with logging turned on but not a single error coming from kodi-connect. 
It scans the library for a second or 2, than after 1 minute almost exactly it just closes:
"DEBUG <general>: [KodiConnect] Connection closed "

But like I said not a single error. I am not sure if this helps, but again thank you for the work you have done on this addon and I can not wait until the day you get it working with 19.

**Comment by BUGBEAR7** [comment]
Hello tkislan 

Sorry to bother you agin but is there any update on this ?
I switched back to 18.9 just because of this addon . So that is why I was unable to give the Kodi 19 log. But I guess you got the log 

We are waiting for this 

Thanks

**Comment by tkislan** [comment]
I apologise, that I've still haven't been able to get to this .. but I do have it in my TODO list, as I also plan to upgrade my device to Kodi 19 aswell

**Comment by flos06** [comment]
Have you upgraded your device yet?

**Comment by tkislan** [comment]
[plugin.video.kodiconnect-0.3.3.zip](https://github.com/kodi-connect/kodi-connect-addon/files/7167998/plugin.video.kodiconnect-0.3.3.zip)

Can you please try this version?

It is working on my Kodi box, but just want to confirm, that it works for others as well

**Comment by Motisu** [comment]
Works just fine! Thank you for the effort!



Thanks,

Moti

P Please consider your environmental responsibility before printing this e-mail

**Comment by Motisu** [comment]
Major problem.  I have 2 Kodi platforms, 1 is a kodi box running Coreelec and the second is an intel NUC running Libreelec. both are running Kodi Matrix and both are registered at the connect site.  The new 3.3 version runs well on the Coreelec box, but I get an error the second that I start it on the Libreelec box.  Can you please look into this?

**Comment by tkislan** [comment]
@Motisu 
Can you please share kodi debug log so that I can try to resolve the issue

**Comment by Motisu** [comment]
sure. here it is
[kodi.log](https://github.com/kodi-connect/kodi-connect-addon/files/7190601/kodi.log)
.

**Comment by tkislan** [comment]
@Motisu 
Can you give this version a try?
https://kodi-connect.s3.eu-central-1.amazonaws.com/kodi-connect-addon/3.0.0/plugin.video.kodiconnect-0.3.4.zip

**Comment by Motisu** [comment]
sorry,but it didnt work. I uninstalled the old version and installed the new one. same problem.  Here is an upload of the relavant part of the log
[kodi.log](https://github.com/kodi-connect/kodi-connect-addon/files/7192731/kodi.log)
:

**Comment by tkislan** [comment]
@Motisu I'm fairly confident, that this version should fix it
https://kodi-connect.s3.eu-central-1.amazonaws.com/kodi-connect-addon/3.0.0/plugin.video.kodiconnect-0.3.5.zip

**Comment by Motisu** [comment]
@tkislan 
Sorry it took so long to test & get back to you. It still throws an error right after starting.  Here is the new log
[kodi.log](https://github.com/kodi-connect/kodi-connect-addon/files/7204882/kodi.log)
.

**Comment by flos06** [comment]
Hi thanks for updating the addon.
While it now stays connected it doesnt actually do anything with the commands. Alexa, pause for example doesnt do anything while alexa watch movie interstellar gives the output from alexa: Getting interstellar from kodi. However nothing happens.
Any ideas?

**Comment by tkislan** [comment]
@flos06 some debug logs from kodi would be useful if I am to help you

**Comment by flos06** [comment]
I think the issue had to do with some of my previous tries. I've deleted everything and started from scratch. Works wonders now!
Thanks for the update I love it!

**Comment by Motisu** [comment]
@tkislan 
were my latest logs useful? are you missing anything that I can help with?

**Comment by Marcagodbout** [comment]
neither of these worked for me, I am not able to get it connected, it just throws an error. One thing I did not do is rebuild the alexa skill. Would I need to start that from scratch too, or should it work with this build?

**Comment by tkislan** [comment]
@Marcagodbout no, it is enough to just update the addon
If it throws error, can you please share a debug kodi log file?

**Comment by BUGBEAR7** [comment]
Hello tkislan

I have installed fresh Kodi 19.1 , tested 0.3.3, 0.3.4, and 0.3.5 
None of the version worked . It gives error just after installation.  
[log 0.3.5.txt](https://github.com/kodi-connect/kodi-connect-addon/files/7258891/log.0.3.5.txt)
[log 0.3.3.txt](https://github.com/kodi-connect/kodi-connect-addon/files/7258893/log.0.3.3.txt)
[log 0.3.4.txt](https://github.com/kodi-connect/kodi-connect-addon/files/7258894/log.0.3.4.txt)

**Comment by BUGBEAR7** [comment]
Hello 
Any update on this ?

**Comment by Kodialexalover** [comment]
> [plugin.video.kodiconnect-0.3.3.zip](https://github.com/kodi-connect/kodi-connect-addon/files/7167998/plugin.video.kodiconnect-0.3.3.zip)
> 
> Can you please try this version?
> 
> It is working on my Kodi box, but just want to confirm, that it works for others as well

"plugin.video.kodiconnect-0.3.3.zip" İt's working in kodi 19.3 version, thank you man :)

**Comment by bamcdowal** [comment]
> @tkislan were my latest logs useful? are you missing anything that I can help with?

@Motisu I'm having this same issue - Libreelec 10. My logs look the same as yours - did you have any luck getting this to work? @tkislan is this something that you are still working on? Thanks for your efforts so far.

**Comment by LuKePicci** [comment]
Same here, kodi win10, did try 0.3.3 only. It looks related to https://stackoverflow.com/questions/60359157/valueerror-set-wakeup-fd-only-works-in-main-thread-on-windows-on-python-3-8-wit

**Comment by tkislan** [comment]
@LuKePicci Thank you for the pointer
I was starting to worry, that I would need to completely reimplement the addon

I've added the workaround into the new version, can you please give it a try?
[plugin.video.kodiconnect-0.3.4.zip](https://github.com/kodi-connect/kodi-connect-addon/files/7798775/plugin.video.kodiconnect-0.3.4.zip)

**Comment by LuKePicci** [comment]
I will try in a few hours, I was trying to determine the actual version of python in Kodi UWP to see if it really is less then 3.8.2 but I can't find it anywhere in the logs.

**Comment by LuKePicci** [comment]
I will try in a few hours, I was trying to determine the actual version of python in Kodi UWP to see if it really is less then 3.8.2 but I can't find it anywhere in the logs.

**Comment by LuKePicci** [comment]
Latest 0.3.4 works GJ

Now I have to figure why "Alexa, go to channel _number_" doesn't work, but that's another story. Thank you for the quick fix.

**Comment by tkislan** [comment]
@LuKePicci Channel controls are not implemented
I had no way to test it, so I never got to implement it

**Comment by LuKePicci** [comment]
I would be happy to be a tester if you like.

**Comment by Motisu** [comment]
Hi Tomas,
I tried the new version but unfortunately, it still crashes.  Here is an edited log of the crash.
BTW, I also use channel PVR so if you need another tester, I'd be very happy to volunteer
[kodi.log](https://github.com/kodi-connect/kodi-connect-addon/files/7799150/kodi.log)
.

**Comment by BUGBEAR7** [comment]
@LuKePicci 
What version of Kodi are you using and the type of installation  I mean in which os you are using it ?

**Comment by LuKePicci** [comment]
@BUGBEAR7 Win10 x64 21H2, Kodi 19.3 from the Store. It is using the builtin python interpreter, not the one installed into the OS. My issue was the same as @Kodialexalover

**Comment by LuKePicci** [comment]
The error in @Motisu log is the same as it was on its September log and it's not related to mine.

**Comment by LuKePicci** [comment]
I see @Motisu is using Linux, AFAIK it uses the Python runtime from the OS environment, so I'd suggest you update it to 3.8 at least,

**Comment by Motisu** [comment]
I am using Linux, sort of.  This a an Intel NUC box and it is running Libreelec.  So technically, it is Linux, but not a version that I would like to start messing around with at that level.

**Comment by captainfearless** [comment]
hi tkislan, i have tried https://github.com/kodi-connect/kodi-connect-addon/files/7798775/plugin.video.kodiconnect-0.3.4.zip but it failed to connect. Would you kindly take a look?
[kodi.log](https://github.com/kodi-connect/kodi-connect-addon/files/7821720/kodi.log)

**Comment by tkislan** [comment]
@captainfearless 
That is a very weird error .. it fails with certificate being expired, but when visiting the web page, certificate is valid until "Expires: Tuesday, 1 March 2022"

**Comment by captainfearless** [comment]
Yes i read that, but didn’t know what an SSL certificate was!

What’s my best plan of attack?, start from scratch?

**Comment by LuKePicci** [comment]
Looks like it's client has the old let's encrypt cert.

I think it's all in a transitioning state, python3 in Kodi is not mature enough, libreelec has old python ecc.
________________________________

**Comment by captainfearless** [comment]
So what should i do boys?, leave it installed and keep trying? I‘ve been waiting for the return of my number 1 add on, and now it’s back i can’t use it!

**Comment by tkislan** [comment]
@captainfearless Sorry, but I actually don't know Windows platform that well, to be able to solve this issue
It seems like it has outdated certificates installed? Because I'm using Letsencrypt as SSL certificate provider, which is pretty standard

**Comment by captainfearless** [comment]
Thanks for clarifying Tomas, and for responding as always. I didn’t realise the SSL issue was a local one! I will google and resolve that way.

Paul Constance

**Comment by LuKePicci** [comment]
@tkislan I think @captainfearless is not using Windows otherwise it's CA certs would have been updated. I guess it is using an old kodi box/distro which has not been updated with new CA certs.

CA cert of Let's Encrypt is expired a few months ago, old boxes without the new CA would not connect anymore to Let's Encrypt HTTPS websites.

Once again I confirm this add-on now works fine on Windows (UWP Kodi version 19.3)

**Comment by captainfearless** [comment]
Hi, just to confirm, i am running kodi on a PC with Windows 10, i am just 1 update behind, which is installing now.

**Comment by captainfearless** [comment]
Log is the same after updating, also manually imported a new certificate earlier.

**Comment by captainfearless** [comment]
Over on the Kodi forums i received this explanation.

your target server https://138.68.100.216 is using a self-signed certificate, which is unknown to kodi.
You should use a proper DNS name and valid certificate.

I'm confused by all of this, all i did was install a new version of Kodi Connect on a previously working set up.

Is the target server my home PC? If so how can i ''use a proper DNS name and valid certificate''

**Comment by captainfearless** [comment]
Well i updated my Python package which didn’t fix it. It’s one of those things where some random update will fix it, so i’ll keep reinstalling.

**Comment by LuKePicci** [comment]
> your target server https://138.68.100.216 is using a self-signed certificate, which is unknown to kodi. You should use a proper DNS name and valid certificate.

I'm not sure they correctly troubleshot this. I mean. that IP is the correct IP address of kodi-connect services, but when you contact that IP with correct hostname it responds with a valid certificate and no error is givem.

It is correct for that IP to respond with sucj invalid self-signed cert when you reach it without using the kodi-connect hostname.

So, why your kodi is using https://IP and not https://kodiconnect.kislan.sk/ ? I'm under windows too and its working fine here so this is a bit strange at least.  Maybe you could try from another windows box?

**Comment by captainfearless** [comment]
I do appreciate your interest Luke. I’m baffled, i wonder if there is a way of forcing it to connect to https://kodiconnect.kislan.sk/? I was also wondering if my VPN could be the cause?

**Comment by LuKePicci** [comment]
Ok, it is definitely worth to try without the VPN. Also if you link us the Kodi forum where you asked for help I would be interested in reading it.

**Comment by captainfearless** [comment]
https://forum.kodi.tv/showthread.php?tid=366429

I will try again without the VPN.

**Comment by captainfearless** [comment]
Still failed. Also when Kodi Connect is installed, Kodi hangs on exiting.

**Comment by LuKePicci** [comment]
I confirm the troubleshoot done on kodi forums is likely wrong. The ssl error clearly states the cert is **expired** which has nothing to do with self-signing. As additional proof of what I'm saying, that self-signed cert is not expired.

The user on kodi forum has been fooled by that misleading error message where the pure IP is shown.

Try visiting https://kodiconnect.kislan.sk/ from your PC, using different browsers and see if any of them gives you certificate errors. Make sure you have no expired certs in their respective cert stores. If none of them give errors and you have no expired CA certs installed, then Kodi (or the Python interpreter) is using its own CA store and there is no valid CA for letsencrypt in there.

Try using Kodi UWP (Windows Store) if you didn't so far.

**Comment by captainfearless** [comment]
Update! My PC died, so i had to reset it, and now KC is working perfectly.

**Comment by Motisu** [comment]
Hi Tkislan,
Anything new with this bug? can I hope for it to be closed or should I just give up? :(

**Comment by tkislan** [comment]
@Motisu 
I will revisit this .. but to be honest, it will most likely require a lot bigger rewrite to support all the different platforms
No idea why it has such different behaviours with different platforms and different Python versions ...

**Comment by Motisu** [comment]
Well, thanks for trying.  I am managing without it now on my main box but it runs very well on my bedroom TV.  I guess a 1/2 is better than none, and I wish you good luck in solving the bug.  I'll still be waiting patiently. :-)

**Comment by ZedeN1** [comment]
I get the same/very simmilar error as @Motisu on Kodi 19.4 running LibreELEC 10.0.2 on Rasberry Pi 4B. Log file: https://paste.kodi.tv/aqukugonov.kodi

**Comment by karl500** [comment]
Hi @tkislan,

Firstly thank you for this great add-on and also for the time and effort you have put into this. 
Unfortunately i'm still having some issues.
When i run the add-on it exits with an error that there is no event loop in thread where the connection to your site is started.
I also looked into it a little bit and there seems to be some kind of change in asyncio where the creation of event loops is not done automatically in threads anymore.

Anyway, if you can please look into it further, it would be much appreciated.

Here's a link to the issue i found: https://stackoverflow.com/questions/51038793/error-happen-python3-6-while-using-tornado-in-multi-threading

and also my debug log fro
[kodi.log](https://github.com/kodi-connect/kodi-connect-addon/files/9749473/kodi.log)
m kodi:

**Comment by MartinsVision** [comment]
Is this up and running yet ?? Great app by the way 👏

**Comment by hindsight2021** [comment]
I had success asking GPT4 to fix the addon, give this a try ya’ll - it worked for me on Kodi v21 omega.

[plugin.video.kodiconnect-0.3.6-fixed.zip](https://github.com/kodi-connect/kodi-connect-addon/files/13199159/plugin.video.kodiconnect-0.3.6-fixed.zip)

Update - once the skill was connected after I updated with my zip in kodi I have full control w/alexa again. I hope it works for you too.

## Changelog for `plugin.video.kodiconnect-0.3.6-fixed`

### Fixed
- **Python Compatibility**: Updated the import statement in `resources/lib/tornado/httputil.py` to address compatibility issues with recent Python versions.
  - Replaced `collections.MutableMapping` with `collections.abc.MutableMapping` to fix the `AttributeError: module 'collections' has no attribute 'MutableMapping'` error.

### Notes
- A warning about the use of a slow pure-python `SequenceMatcher` from the `fuzzywuzzy` library still persists. It suggests installing `python-Levenshtein` to remove this warning. While this warning does not impact the functionality of the addon, it might affect performance. Depending on the use-case, it can be considered for future optimization.

### Developer's Changelog for `plugin.video.kodiconnect-0.3.6-fixed`

### Detailed Modifications:

1. **File**: `resources/lib/tornado/httputil.py`
   - **Change**: Updated the import statement for compatibility with recent Python versions.
   - **Original Line**: `class HTTPHeaders(collections.MutableMapping):`
   - **Modified Line**: `class HTTPHeaders(collections.abc.MutableMapping):`

**Comment by MartinsVision** [comment]
I can now connect but no commands work from Alexa

**Comment by captainfearless** [comment]
Has anyone currently got this working?

**Comment by MartinsVision** [comment]
I haven't yet
